version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '21:00'
      timezone: 'Asia/Tokyo'
    assignees:
      - 'kohdice'
      - 'kazumasato0214'
    commit-message:
      prefix: 'npm'
    versioning-strategy: lockfile-only

  - package-ecosystem: 'docker'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '21:00'
      timezone: 'Asia/Tokyo'
    assignees:
      - 'kohdice'
      - 'kazumasato0214'
    commit-message:
      prefix: 'docker'

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '21:00'
      timezone: 'Asia/Tokyo'
    assignees:
      - 'kohdice'
      - 'kazumasato0214'
    commit-message:
      prefix: 'actions'
