name: stylelint

on:
  push

jobs:
  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-check
          stylelint_input: 'app/styles/**/*.css'
